### ISSUE TITLE
`IVisionMsgs2DDetectionArray` not available in typescript library

### ISSUE THREAD

**Issue by entire** [faust-computer/geist_common#2]
from @sixmoraltales:

<img width="734" alt="Screenshot 2023-11-06 at 11 25 23" src="https://github.com/faust-computer/geist_common/assets/444016/7aaeaee3-5fc5-44d0-a962-4c8e97715063">

> Looking for the right mobilenet module to import from geist_common. The roughed-in demo project code tries to import "IVisionMsgs2DDetectionArray" from geist_common but after adding the geist_common submodule to the repo this module is still not found.

link: https://github.com/faust-computer/geist_common/blob/7ce048d3cdd597e9ba85149eaaecdc03b355111d/src/index.ts

@Chrismacolor - do you want to look into this?

**Comment by Chrismacolor** [comment]
Thank you for pointing this out.  This is because geist_common has not been updated to include the vision msgs.  As discussed with @entire the bigger solve is to make typescript support easier to update and maintain, this includes but is not limited to:

- Fix naming structure on msgs
- Add necessary CI and tagging to update geist_common with each new version
- Document type generation process for better maintainability

**Comment by entire** [comment]
Seems like #6 will fix this

**Comment by Chrismacolor** [comment]
Fixed by https://github.com/faust-computer/geist_common/pull/6
